### PR TITLE
ENH - add ``benchmark_utils`` for reusable code across the benchmark directory

### PR DESCRIPTION
**Pull request by Badr-MOUFAD**
thanks to https://github.com/benchopt/benchopt/pull/472,
now it's possible to import directly reusable code in solvers, datafits, and objectives

This adds a ``benchmark_utils`` folder and informative comments to account for that.

### CODE REVIEW

**Comment by tomMoral** [comment]
I am mostly -1 on this one as I think this complexify the template and does not make it easier to use.
I think the template should present the most basic benchmark fact, with potential link to advanced features in the `README`.

But happy to discuss if you think this is important to have this one.

**Comment by Badr-MOUFAD** [comment]
It doesn't add much to the template and might hint at the way of reusing code across the benchmark directory.
But, I definitely agree with you!
Let's keep it simple.

**Comment by mathurinm** [comment]
I'm the one who asked Badr to send the PR so obviously I'm rather +1 :D 

I think it's a vital feature for any benchmark and thus deserves to be in the template (this way the module has the correct name from the start). 

But I'd make it simpler by defining a single function in `__init__.py` (not a dummy one) and importing it only in objective or solver or dataset), so the diff concerns only 2 files.

**Review by mathurinm — APPROVED** [review]

**Comment by mathurinm** [comment]
Thank you @Badr-MOUFAD !

**Pull request merged**
